import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useTheme, type Theme } from '../../theme/theme';
import { useThemeMode } from '../../theme/ThemeContext';

const SECTIONS = [
  {
    title: '1. Who We Are',
    body: 'MineOps ("we", "us", "our") operates the MineOps mobile application. This Privacy Policy explains what personal data we collect, why we collect it, and how it is used and protected.',
  },
  {
    title: '2. Data We Collect',
    body: 'We collect information you provide directly (name, email, phone, role, assigned site, profile photo), data generated by your use of the App (clock-in/out times, incident reports, SOS alerts, hazard submissions, safety checklists), device information (device name, platform, OS version), and session tokens for authentication.',
  },
  {
    title: '3. How We Use Your Data',
    body: 'Your data is used to operate and secure your account, enable site operations and safety features, allow supervisors to manage worker attendance and incidents, generate reports for site administrators, and comply with legal and regulatory obligations.',
  },
  {
    title: '4. Safety-Critical Data',
    body: 'Incident reports, SOS alerts, and hazard reports are shared with your designated supervisors and safety officers. This sharing is inherent to the safety purpose of the App and cannot be opted out of while using safety features.',
  },
  {
    title: '5. Buyer & Marketplace Data',
    body: 'For buyer accounts, we collect business registration details, GoldBod license numbers, and verification documents. This information is used for identity verification and may be shared with regulatory bodies as required by law.',
  },
  {
    title: '6. Device & Location',
    body: 'When you submit an incident or illegal mine report, precise GPS coordinates may be captured and stored alongside the report. Device information is collected to enable session management and security features.',
  },
  {
    title: '7. Data Retention',
    body: 'Account data is retained for as long as your account is active and for a period thereafter as required by applicable law. Safety records (incidents, SOS alerts) may be retained longer to comply with mining safety regulations.',
  },
  {
    title: '8. Data Security',
    body: 'Passwords are stored using bcrypt hashing. Refresh tokens are rotated on each use. All API communication is encrypted via HTTPS. We do not store payment card data.',
  },
  {
    title: '9. Sharing with Third Parties',
    body: 'We do not sell your personal data. We may share data with cloud infrastructure providers for hosting, and with regulatory or law enforcement authorities where legally required. Site operators have access to the operational data of workers at their site.',
  },
  {
    title: '10. Your Rights',
    body: 'Depending on your jurisdiction, you may have the right to access, correct, or delete your personal data. Requests can be sent to support@mineops.app. Some data may need to be retained to comply with legal obligations.',
  },
  {
    title: '11. Children',
    body: 'The App is not intended for use by persons under 18. We do not knowingly collect data from minors. If you believe a minor has registered, contact us immediately.',
  },
  {
    title: '12. Changes to This Policy',
    body: 'We may update this Privacy Policy periodically. The updated version will be indicated by a revised effective date, and you will be notified within the App of material changes.',
  },
];

export function PrivacyPolicyScreen() {
  const { mode } = useThemeMode();
  const theme = useTheme(mode);
  const styles = makeStyles(theme);

  return (
    <ScrollView contentContainerStyle={styles.container} showsVerticalScrollIndicator={false}>
      <Text style={styles.pageTitle}>Privacy Policy</Text>
      <Text style={styles.pageSub}>Effective date: July 2026</Text>

      <View style={styles.draftBanner}>
        <Text style={styles.draftText}>⚠️ This Privacy Policy is in draft form and subject to change before the App's official public release.</Text>
      </View>

      {SECTIONS.map((s) => (
        <View key={s.title} style={styles.section}>
          <Text style={styles.sectionTitle}>{s.title}</Text>
          <Text style={styles.sectionBody}>{s.body}</Text>
        </View>
      ))}

      <Text style={styles.contact}>Data queries: support@mineops.app</Text>
    </ScrollView>
  );
}

function makeStyles(theme: Theme) {
  return StyleSheet.create({
    container: { padding: 20, paddingBottom: 48 },
    pageTitle: { color: theme.text, fontSize: 24, fontWeight: '900', marginBottom: 4 },
    pageSub: { color: theme.textMuted, fontSize: 12, fontWeight: '600', marginBottom: 16 },
    draftBanner: { backgroundColor: theme.amberLight, borderColor: theme.amber, borderLeftWidth: 4, borderRadius: 8, borderWidth: 1, marginBottom: 24, padding: 12 },
    draftText: { color: theme.amber, fontSize: 12, fontWeight: '700', lineHeight: 18 },
    section: { marginBottom: 20 },
    sectionTitle: { color: theme.text, fontSize: 15, fontWeight: '900', marginBottom: 6 },
    sectionBody: { color: theme.textSub, fontSize: 13, fontWeight: '500', lineHeight: 20 },
    contact: { color: theme.textMuted, fontSize: 12, fontWeight: '600', marginTop: 8, textAlign: 'center' },
  });
}
